name: Deploy Front Docker

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  deploy_front:
    if: github.repository == 'ldurans/izing.open.io'
    runs-on: ubuntu-22.04 
    environment: production 
    steps:
      - name: "Checkout" 
        uses: actions/checkout@v4

      - name: "Use NodeJS"          
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
    
      - name: Verify Node.js version
        run: node -v
    
      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Frontend
        run: |
          cd frontend
          export NODE_OPTIONS=--openssl-legacy-provider
          npx quasar build -P -m pwa

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: izingopenio
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t izingopenio/izingopenio-frontend:latest --push ./frontend
